export const terminalCapabilities = {
  ghostty: {
    name: "Ghostty",
    level: "full",
    format: ".conf",
    colors: true,
    wallpaper: true,
    opacity: true,
    blur: true,
    padding: true,
    cursor: true,
    decorations: true,
    panes: true,
  },
  wezterm: {
    name: "WezTerm",
    level: "full",
    format: ".lua",
    colors: true,
    wallpaper: true,
    opacity: true,
    blur: true,
    padding: true,
    cursor: true,
    decorations: true,
    panes: true,
  },
  kitty: {
    name: "Kitty",
    level: "full",
    format: ".conf",
    colors: true,
    wallpaper: true,
    opacity: true,
    blur: true,
    padding: true,
    cursor: true,
    decorations: true,
    panes: true,
  },
  iterm2: {
    name: "iTerm2",
    level: "visual",
    format: "Dynamic Profile JSON",
    colors: true,
    wallpaper: true,
    opacity: true,
    blur: true,
    padding: false,
    cursor: true,
    decorations: false,
    panes: false,
    note: "Split dimming and margins are app-wide preferences and stay user-owned.",
  },
  terminal: {
    name: "Apple Terminal",
    level: "visual",
    format: ".terminal",
    colors: true,
    wallpaper: true,
    opacity: true,
    blur: true,
    padding: false,
    cursor: true,
    decorations: false,
    panes: false,
  },
  warp: {
    name: "Warp",
    level: "visual",
    format: ".yaml",
    colors: true,
    wallpaper: true,
    opacity: false,
    blur: false,
    padding: false,
    cursor: true,
    decorations: false,
    panes: false,
    note: "Window opacity, blur, and pane dimming are global Warp settings, not theme YAML fields.",
  },
  alacritty: {
    name: "Alacritty",
    level: "native",
    format: ".toml",
    colors: true,
    wallpaper: false,
    opacity: true,
    blur: true,
    padding: true,
    cursor: true,
    decorations: true,
    panes: false,
    note: "Alacritty has no native background-image or pane system.",
  },
};

export const capabilityLabels = {
  full: "Full Experience",
  visual: "Visual Profile",
  native: "Native Styling",
};
