import path from "node:path";

const clean = (color) => color.replace("#", "");
const xmlEscape = (value) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;");

export const targets = ["ghostty", "kitty", "alacritty", "wezterm", "iterm2"];

export function exportTheme(theme, target) {
  if (!targets.includes(target)) throw new Error(`Unknown target "${target}". Choose: ${targets.join(", ")}.`);
  return exporters[target](theme);
}

export function extensionFor(target) {
  return { ghostty: "conf", kitty: "conf", alacritty: "toml", wezterm: "lua", iterm2: "itermcolors" }[target];
}

export function ghostty(theme) {
  const lines = [
    `# ${theme.name} — generated by Termdeck`,
    `background = ${theme.background}`,
    `foreground = ${theme.foreground}`,
    `cursor-color = ${theme.cursor}`,
    `selection-background = ${theme.selectionBackground}`,
    `selection-foreground = ${theme.selectionForeground || theme.foreground}`,
  ];
  theme.palette.forEach((color, index) => lines.push(`palette = ${index}=${color}`));
  return `${lines.join("\n")}\n`;
}

export function kitty(theme) {
  const names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"];
  const lines = [
    `# ${theme.name} — generated by Termdeck`,
    `background ${theme.background}`,
    `foreground ${theme.foreground}`,
    `cursor ${theme.cursor}`,
    `selection_background ${theme.selectionBackground}`,
    `selection_foreground ${theme.selectionForeground || theme.foreground}`,
  ];
  theme.palette.forEach((color, index) => lines.push(`color${index} ${color} # ${index > 7 ? "bright " : ""}${names[index % 8]}`));
  return `${lines.join("\n")}\n`;
}

export function alacritty(theme) {
  const [b, r, g, y, bl, m, c, w, bb, br, bg, by, bbl, bm, bc, bw] = theme.palette;
  return `# ${theme.name} — generated by Termdeck
[colors.primary]
background = "${theme.background}"
foreground = "${theme.foreground}"

[colors.cursor]
cursor = "${theme.cursor}"
text = "${theme.background}"

[colors.selection]
background = "${theme.selectionBackground}"
text = "${theme.selectionForeground || theme.foreground}"

[colors.normal]
black = "${b}"
red = "${r}"
green = "${g}"
yellow = "${y}"
blue = "${bl}"
magenta = "${m}"
cyan = "${c}"
white = "${w}"

[colors.bright]
black = "${bb}"
red = "${br}"
green = "${bg}"
yellow = "${by}"
blue = "${bbl}"
magenta = "${bm}"
cyan = "${bc}"
white = "${bw}"
`;
}

export function wezterm(theme) {
  const quoted = (colors) => colors.map((color) => `"${color}"`).join(", ");
  return `-- ${theme.name} — generated by Termdeck
return {
  foreground = "${theme.foreground}",
  background = "${theme.background}",
  cursor_bg = "${theme.cursor}",
  cursor_fg = "${theme.background}",
  selection_bg = "${theme.selectionBackground}",
  selection_fg = "${theme.selectionForeground || theme.foreground}",
  ansi = { ${quoted(theme.palette.slice(0, 8))} },
  brights = { ${quoted(theme.palette.slice(8))} },
}
`;
}

function hexToComponents(color) {
  const hex = clean(color);
  return [0, 2, 4].map((index) => Number.parseInt(hex.slice(index, index + 2), 16) / 255);
}

function itermColor(key, color) {
  const [r, g, b] = hexToComponents(color);
  return `  <key>${xmlEscape(key)}</key>
  <dict>
    <key>Color Space</key><string>sRGB</string>
    <key>Red Component</key><real>${r.toFixed(6)}</real>
    <key>Green Component</key><real>${g.toFixed(6)}</real>
    <key>Blue Component</key><real>${b.toFixed(6)}</real>
    <key>Alpha Component</key><real>1</real>
  </dict>`;
}

export function iterm2(theme) {
  const entries = [
    ...theme.palette.map((color, index) => [`Ansi ${index} Color`, color]),
    ["Background Color", theme.background],
    ["Foreground Color", theme.foreground],
    ["Bold Color", theme.foreground],
    ["Cursor Color", theme.cursor],
    ["Cursor Text Color", theme.background],
    ["Selection Color", theme.selectionBackground],
    ["Selected Text Color", theme.selectionForeground || theme.foreground],
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
${entries.map(([key, color]) => itermColor(key, color)).join("\n")}
</dict>
</plist>
`;
}

export function defaultOutput(theme, target, cwd = process.cwd()) {
  return path.join(cwd, "dist", target, `${theme.slug}.${extensionFor(target)}`);
}

const exporters = { ghostty, kitty, alacritty, wezterm, iterm2 };
