import path from "node:path";
import { terminalCapabilities } from "./capabilities.js";
import { getProfile } from "./profiles.js";

const clean = (color) => color.replace("#", "");
const names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"];

export const targets = Object.keys(terminalCapabilities);

function settings(options = {}) {
  const profile = options.profile || getProfile(options.profileName || "cozy");
  const values = profile.options;
  const number = (key, fallback) => Number.parseFloat(values[key] ?? fallback);
  const blurValue = values["background-blur"];
  return {
    opacity: number("background-opacity", 0.94),
    blur: blurValue === "false" || blurValue === false ? 0 : Number.parseFloat(blurValue || 0),
    paddingX: number("window-padding-x", 14),
    paddingY: number("window-padding-y", 12),
    inactiveOpacity: number("unfocused-split-opacity", 0.76),
    cursor: values["cursor-style"] || "block",
    cursorBlink: String(values["cursor-style-blink"]) === "true",
    titlebar: values["macos-titlebar-style"] || "tabs",
    wallpaperPath: options.wallpaperPath || path.posix.join("assets", path.basename(options.theme?.wallpaper || "wallpaper.png")),
  };
}

export function exportTheme(theme, target, options = {}) {
  if (!targets.includes(target)) throw new Error(`Unknown target "${target}". Choose: ${targets.join(", ")}.`);
  return exporters[target](theme, { ...options, theme });
}

export function extensionFor(target) {
  return { ghostty: "conf", kitty: "conf", iterm2: "json", warp: "yaml", alacritty: "toml" }[target];
}

export function ghostty(theme, options = {}) {
  const config = settings(options);
  const lines = [
    `# ${theme.name} v${theme.version} — generated by Termdeck`,
    `background = ${theme.background}`,
    `foreground = ${theme.foreground}`,
    `cursor-color = ${theme.cursor}`,
    // The character under a block cursor, which is otherwise left to a default
    // that can sit unreadably close to the accent the cursor is painted in.
    `cursor-text = ${theme.background}`,
    `selection-background = ${theme.selectionBackground}`,
    `selection-foreground = ${theme.selectionForeground || theme.foreground}`,
    // Ghostty colours more than the classic sixteen. Left unset, these keep
    // their defaults — a grey divider and a golden-yellow search highlight —
    // which look identical whichever theme is applied. The slots reused here are
    // the same ones every other exporter already uses for the same purposes: the
    // bright black as the border tone, the yellow as the highlight, the accent
    // for whatever the reader is looking for right now.
    `split-divider-color = ${theme.palette[8]}`,
    `search-foreground = ${theme.background}`,
    `search-background = ${theme.palette[3]}`,
    `search-selected-foreground = ${theme.background}`,
    `search-selected-background = ${theme.cursor}`,
  ];
  lines.push(...theme.palette.map((color, index) => `palette = ${index}=${color}`));
  if (options.full !== false) {
    lines.push(
      "",
      `background-image = ${config.wallpaperPath}`,
      `background-image-opacity = ${theme.wallpaperOpacity || "0.18"}`,
      "background-image-fit = cover",
      "background-image-position = center",
      "background-image-repeat = false",
      ...Object.entries(options.profile?.options || getProfile(options.profileName || "cozy").options).map(([key, value]) => `${key} = ${value}`),
    );
  }
  return `${lines.join("\n")}\n`;
}

export function kitty(theme, options = {}) {
  const config = settings(options);
  const cursorShape = { bar: "beam", underline: "underline" }[config.cursor] || "block";
  const decorations = config.titlebar === "hidden" ? "yes" : config.titlebar === "transparent" ? "titlebar-only" : "no";
  const lines = [
    `# ${theme.name} v${theme.version} — Termdeck Full Experience`,
    `background ${theme.background}`,
    `foreground ${theme.foreground}`,
    `cursor ${theme.cursor}`,
    `cursor_text_color ${theme.background}`,
    `cursor_shape ${cursorShape}`,
    `cursor_blink_interval ${config.cursorBlink ? "0.5" : "0"}`,
    `selection_background ${theme.selectionBackground}`,
    `selection_foreground ${theme.selectionForeground || theme.foreground}`,
    "",
    `background_image ${config.wallpaperPath}`,
    "background_image_layout cscaled",
    `background_tint ${(1 - Number(theme.wallpaperOpacity || 0.18)).toFixed(2)}`,
    `background_opacity ${config.opacity}`,
    `background_blur ${config.blur}`,
    "dynamic_background_opacity yes",
    "",
    `window_padding_width ${config.paddingY} ${config.paddingX} ${config.paddingY} ${config.paddingX}`,
    "placement_strategy center",
    `hide_window_decorations ${decorations}`,
    `inactive_text_alpha ${config.inactiveOpacity}`,
    `active_border_color ${theme.cursor}`,
    `inactive_border_color ${theme.palette[8]}`,
    "draw_minimal_borders yes",
    "",
  ];
  lines.push(...theme.palette.map((color, index) => `color${index} ${color} # ${index > 7 ? "bright " : ""}${names[index % 8]}`));
  return `${lines.join("\n")}\n`;
}

export function alacritty(theme, options = {}) {
  const config = settings(options);
  const [b, r, g, y, bl, m, c, w, bb, br, bg, by, bbl, bm, bc, bw] = theme.palette;
  const cursorShape = { bar: "Beam", underline: "Underline" }[config.cursor] || "Block";
  const decorations = config.titlebar === "hidden" ? "None" : config.titlebar === "transparent" ? "Transparent" : "Full";
  return `# ${theme.name} v${theme.version} — Termdeck Native Styling
[window]
opacity = ${config.opacity}
blur = ${config.blur > 0}
decorations = "${decorations}"
dynamic_padding = true

[window.padding]
x = ${config.paddingX}
y = ${config.paddingY}

[cursor]
style = { shape = "${cursorShape}", blinking = "${config.cursorBlink ? "On" : "Off"}" }
unfocused_hollow = true

[colors.primary]
background = "${theme.background}"
foreground = "${theme.foreground}"

[colors.cursor]
cursor = "${theme.cursor}"
text = "${theme.background}"

[colors.selection]
background = "${theme.selectionBackground}"
text = "${theme.selectionForeground || theme.foreground}"

[colors.normal]
black = "${b}"
red = "${r}"
green = "${g}"
yellow = "${y}"
blue = "${bl}"
magenta = "${m}"
cyan = "${c}"
white = "${w}"

[colors.bright]
black = "${bb}"
red = "${br}"
green = "${bg}"
yellow = "${by}"
blue = "${bbl}"
magenta = "${bm}"
cyan = "${bc}"
white = "${bw}"
`;
}


function hexToComponents(color) {
  const hex = clean(color);
  return [0, 2, 4].map((index) => Number.parseInt(hex.slice(index, index + 2), 16) / 255);
}

function itermColor(color) {
  const [r, g, b] = hexToComponents(color);
  return {
    "Color Space": "sRGB",
    "Red Component": Number(r.toFixed(6)),
    "Green Component": Number(g.toFixed(6)),
    "Blue Component": Number(b.toFixed(6)),
    "Alpha Component": 1,
  };
}

function stableGuid(slug) {
  let hash = 2166136261;
  for (const character of `termdeck:${slug}`) {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  const part = (hash >>> 0).toString(16).padStart(8, "0");
  return `${part}-7dec-4dec-8dec-${part}${part.slice(0, 4)}`.toUpperCase();
}

export function iterm2(theme, options = {}) {
  const config = settings(options);
  const profile = {
    Name: `Termdeck — ${theme.name}`,
    Guid: stableGuid(theme.slug),
    "Badge Text": `Termdeck · ${theme.name} v${theme.version}`,
    "Background Color": itermColor(theme.background),
    "Foreground Color": itermColor(theme.foreground),
    "Bold Color": itermColor(theme.foreground),
    "Cursor Color": itermColor(theme.cursor),
    "Cursor Text Color": itermColor(theme.background),
    "Selection Color": itermColor(theme.selectionBackground),
    "Selected Text Color": itermColor(theme.selectionForeground || theme.foreground),
    "Background Image Location": config.wallpaperPath,
    "Blend": Number((1 - Number(theme.wallpaperOpacity || 0.18)).toFixed(2)),
    "Transparency": Number((1 - config.opacity).toFixed(2)),
    "Blur": config.blur > 0,
    "Blur Radius": config.blur,
    "Cursor Type": config.cursor === "bar" ? 1 : config.cursor === "underline" ? 2 : 0,
    "Blinking Cursor": config.cursorBlink,
  };
  theme.palette.forEach((color, index) => { profile[`Ansi ${index} Color`] = itermColor(color); });
  return `${JSON.stringify({ Profiles: [profile] }, null, 2)}\n`;
}




export function warp(theme, options = {}) {
  const config = settings(options);
  const colorRows = (colors) => colors.map((color, index) => `    ${names[index]}: '${color}'`).join("\n");
  return `# ${theme.name} v${theme.version} — Termdeck Visual Profile
name: 'Termdeck — ${theme.name}'
accent: '${theme.cursor}'
cursor: '${theme.cursor}'
background: '${theme.background}'
foreground: '${theme.foreground}'
details: darker
background_image:
  path: '${path.basename(config.wallpaperPath)}'
  opacity: ${Math.round(Number(theme.wallpaperOpacity || 0.18) * 100)}
terminal_colors:
  normal:
${colorRows(theme.palette.slice(0, 8))}
  bright:
${colorRows(theme.palette.slice(8))}
`;
}

export function defaultOutput(theme, target, cwd = process.cwd()) {
  return path.join(cwd, "dist", target, `${theme.slug}.${extensionFor(target)}`);
}

const exporters = { ghostty, kitty, iterm2, warp, alacritty };
